import type { Metadata } from 'next'
import '@/app/globals.css'
import dynamic from 'next/dynamic'

// Dynamically import ReduxProvider to ensure it's client-side only

export const metadata: Metadata = {
  title: 'AI-Chat',
  description: 'Generated by Ajithkumar',
}

interface RootLayoutProps {
  children: React.ReactNode;
}
const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <main className='flex flex-col justify-center items-center bg-[#192637] min-h-screen' style={{ backgroundSize: '35%', backgroundPosition: 'left 1em bottom -37px', backgroundRepeat: 'no-repeat', height: '100%' }}>

            {children} {'sdsds'}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;