import type { Metadata } from 'next'
import '@/app/globals.css'
import dynamic from 'next/dynamic'

// Dynamically import ReduxProvider to ensure it's client-side only

export const metadata: Metadata = {
  title: 'AI-Chat',
  description: 'Generated by Ajithkumar',
}

interface RootLayoutProps {
  children: React.ReactNode;
}
const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (<>
  {children}  
  </>
  );
};

export default RootLayout;